# Generated by Django 5.1.4 on 2025-01-13 06:29

import Users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_password_change',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='privacy_agreement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='promotion_agreement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_question',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='service_agreement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigIntegerField(default=Users.models.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='전화번호는 9자에서 15자의 숫자만 포함할 수 있습니다.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['id'], name='Users_custo_id_674f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='Users_custo_email_8e4299_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_locked'], name='Users_custo_is_lock_dc33fb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['code'], name='Users_email_code_4fc6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['is_verified'], name='Users_email_is_veri_606946_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'success', 'login_time'], name='Users_login_user_id_70ad67_idx'),
        ),
    ]
