# Generated by Django 5.1.4 on 2025-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='Users_custo_is_lock_dc33fb_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean')], default='ko', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('user', '일반 사용자')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_account_type',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('github', 'GitHub')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
